### ISSUE TITLE
Remove the bot you didnt develop

### ISSUE THREAD

**Issue by DarkSageRM** [KristofPusztai/Runemate-Bots#1]
Please remove the bot in ur repo that you did NOT develop and should never have been made publicly available

**Comment by KristofPusztai** [comment]
That code was sent to me by another dev to help fix, i did not have time to work on it since then and made it public in case anyone had the time to fix it, along with all the other bots which are probably broken by now as well! I suggest you take a crack at it :)

**Comment by DarkSageRM** [comment]
i am the original developer, i am requesting u take my code out of the public light

**Comment by DarkSageRM** [comment]
look at the xml you will see my name in it

**Comment by KristofPusztai** [comment]
Oh woah 😅 I’ll remove right now! Its been a while, did you ever end up fixing?

**Comment by KristofPusztai** [comment]
deleted
